/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VizijaRouteImport } from './routes/vizija'
import { Route as SkoleRouteImport } from './routes/skole'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZrakGradRouteImport } from './routes/zrak.$grad'
import { Route as EnPartnerRouteImport } from './routes/en.partner'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VizijaRoute = VizijaRouteImport.update({
  id: '/vizija',
  path: '/vizija',
  getParentRoute: () => rootRouteImport,
} as any)
const SkoleRoute = SkoleRouteImport.update({
  id: '/skole',
  path: '/skole',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrakGradRoute = ZrakGradRouteImport.update({
  id: '/zrak/$grad',
  path: '/zrak/$grad',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPartnerRoute = EnPartnerRouteImport.update({
  id: '/en/partner',
  path: '/en/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skole': typeof SkoleRoute
  '/vizija': typeof VizijaRoute
  '/en/partner': typeof EnPartnerRoute
  '/zrak/$grad': typeof ZrakGradRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skole': typeof SkoleRoute
  '/vizija': typeof VizijaRoute
  '/en/partner': typeof EnPartnerRoute
  '/zrak/$grad': typeof ZrakGradRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skole': typeof SkoleRoute
  '/vizija': typeof VizijaRoute
  '/en/partner': typeof EnPartnerRoute
  '/zrak/$grad': typeof ZrakGradRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/partner'
    | '/sitemap.xml'
    | '/skole'
    | '/vizija'
    | '/en/partner'
    | '/zrak/$grad'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/partner'
    | '/sitemap.xml'
    | '/skole'
    | '/vizija'
    | '/en/partner'
    | '/zrak/$grad'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/partner'
    | '/sitemap.xml'
    | '/skole'
    | '/vizija'
    | '/en/partner'
    | '/zrak/$grad'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartnerRoute: typeof PartnerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkoleRoute: typeof SkoleRoute
  VizijaRoute: typeof VizijaRoute
  EnPartnerRoute: typeof EnPartnerRoute
  ZrakGradRoute: typeof ZrakGradRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vizija': {
      id: '/vizija'
      path: '/vizija'
      fullPath: '/vizija'
      preLoaderRoute: typeof VizijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skole': {
      id: '/skole'
      path: '/skole'
      fullPath: '/skole'
      preLoaderRoute: typeof SkoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zrak/$grad': {
      id: '/zrak/$grad'
      path: '/zrak/$grad'
      fullPath: '/zrak/$grad'
      preLoaderRoute: typeof ZrakGradRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/partner': {
      id: '/en/partner'
      path: '/en/partner'
      fullPath: '/en/partner'
      preLoaderRoute: typeof EnPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartnerRoute: PartnerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkoleRoute: SkoleRoute,
  VizijaRoute: VizijaRoute,
  EnPartnerRoute: EnPartnerRoute,
  ZrakGradRoute: ZrakGradRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
